import { Injectable } from '@nestjs/common';
import {
  CoachDashboardPlayerDto,
  CoachDashboardResponseDto,
} from './dto/coach-dashboard-response.dto';

@Injectable()
export class CoachDashboardService {
  getDashboard(): CoachDashboardResponseDto {
    return {
      averageTeamCards: [
        {
          name: 'Média Ofensiva Geral',
          color: 'linear-gradient(135deg, #2563eb, #1e40af)',
          value: '10',
          icon: 'faChartColumn',
        },
        {
          name: 'Média Defensiva Geral',
          color: 'linear-gradient(135deg, #f97316, #c2410c)',
          value: '20',
          icon: 'faChartColumn',
        },
        {
          name: 'Média Geral da Equipe',
          color: 'linear-gradient(135deg, #22c55e, #15803d)',
          value: '10',
          icon: 'faTrophy',
        },
      ],
      metrics: [
        'Minutagem',
        'Gols em quadra',
        'Gols tomados em quadra',
        'Ações defensivas',
        'Ações ofensivas',
      ],
      players: [
        this.player(
          '00000000-0000-4000-8000-000000000201',
          'João',
          98,
          'Fixo',
          31,
          68,
          2,
          7,
          1,
        ),
        this.player(
          '00000000-0000-4000-8000-000000000202',
          'Guga',
          97,
          'Pivo',
          40,
          9,
          52,
          31,
          14,
        ),
        this.player(
          '00000000-0000-4000-8000-000000000203',
          'Guedes',
          96,
          'Ala',
          36,
          42,
          46,
          28,
          10,
        ),
        this.player(
          '00000000-0000-4000-8000-000000000204',
          'Senna',
          99,
          'Ala',
          85,
          18,
          42,
          22,
          18,
        ),
        this.player(
          '00000000-0000-4000-8000-000000000205',
          'Balk',
          95,
          'Fixo',
          25,
          39,
          30,
          23,
          2,
        ),
      ],
      teamIndexes: [
        {
          id: 'positional-attack',
          title: 'Ataque posicional',
          value: 87,
          phase: 'offensive',
          trend: 'up',
          maxValue: 100,
        },
        {
          id: 'playing-out-pressure',
          title: 'Saída de pressão',
          value: 82,
          phase: 'offensive',
          trend: 'up',
          maxValue: 100,
        },
        {
          id: 'fly-goalkeeper',
          title: 'Goleiro linha',
          value: 74,
          phase: 'offensive',
          trend: 'stable',
          maxValue: 100,
        },
        {
          id: 'offensive-transition',
          title: 'Transição ofensiva',
          value: 91,
          phase: 'offensive',
          trend: 'up',
          maxValue: 100,
        },
        {
          id: 'low-block',
          title: 'Marcação baixa',
          value: 78,
          phase: 'defensive',
          trend: 'stable',
          maxValue: 100,
        },
        {
          id: 'variable-defense',
          title: 'Marcação variável',
          value: 80,
          phase: 'defensive',
          trend: 'up',
          maxValue: 100,
        },
        {
          id: 'pressing',
          title: 'Pressing',
          value: 84,
          phase: 'defensive',
          trend: 'up',
          maxValue: 100,
        },
        {
          id: 'defensive-transition',
          title: 'Transição defensiva',
          value: 69,
          phase: 'defensive',
          trend: 'down',
          maxValue: 100,
        },
        {
          id: 'set-piece-fouls',
          title: 'Faltas',
          value: 76,
          phase: 'set-piece',
          trend: 'stable',
          maxValue: 100,
        },
        {
          id: 'set-piece-offensive-throw-in',
          title: 'Lateral ofensivo',
          value: 72,
          phase: 'set-piece',
          trend: 'up',
          maxValue: 100,
        },
        {
          id: 'set-piece-corners',
          title: 'Cantos',
          value: 85,
          phase: 'set-piece',
          trend: 'up',
          maxValue: 100,
        },
      ],
    };
  }

  private player(
    id: string,
    name: string,
    overall: number,
    position: string,
    minutes: number,
    defensiveActions: number,
    offensiveActions: number,
    goalsTaken: number,
    goals: number,
  ): CoachDashboardPlayerDto {
    return {
      id,
      name,
      overall,
      position,
      minutes,
      defensiveActions,
      offensiveActions,
      goalsTaken,
      goals,
      indexes: {
        radj: 2,
        goalsRelations: 2,
        actionsRelations: 2,
        atd: 2,
        dto: 2,
        pgj: 2,
        ic: 2,
        tio: 2,
        gtj: 2,
        rf: 2,
        tid: 2,
      },
    };
  }
}
